<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="first_marvin">

    <!-- Base link measurements -->
    <xacro:property name="base_x" value="0.1565" />
    <xacro:property name="base_y" value="0.141" />
    <xacro:property name="base_z" value="0.0865" />

    <!-- Leg link measurements -->
    <xacro:property name="leg_x" value="0.03" />
    <xacro:property name="leg_y" value="0.01" />
    <xacro:property name="leg_z" value="0.055" />

    <!-- Wheel measurements -->
    <xacro:property name="wheel_diam" value="0.0575" />
    <xacro:property name="wheel_length" value="0.025" />
    <xacro:property name="pi" value="3.14159265359" />

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>
    
    <material name="red">
        <color rgba="1.0 0.0 0.0 1"/>
    </material> 

    <!-- Physics -->
    <xacro:property name="base_effort" value="100"/>
    <xacro:property name="base_velocity" value="0.5"/>

    <!-- inertial macros -->
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
        <mass value="${mass}" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>

    <!-- Base link -->
    <link name="base_link">
        <xacro:default_inertial mass="10"/>
        <visual>
            <origin xyz="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_x} ${base_y} ${base_z}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_x} ${base_y} ${base_z}"/>
            </geometry>
        </collision>
    </link>

    <!-- Leg macro -->
    <xacro:macro name="leg" params="prefix suffix reflect_x reflect_y">
        <link name="${prefix}_${suffix}_leg">
            <visual>
                <geometry>
                    <box size="${leg_x} ${leg_y} ${leg_z}"/>
                </geometry>
                <origin xyz="0.0 0.0 -${leg_z / 2}" rpy="0.0 0 0.0"/>
                <material name="red"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${leg_x} ${leg_y} ${leg_z}"/>
                </geometry>
                <origin xyz="0.0 0.0 -${leg_z / 2}" rpy="0.0 0 0.0"/>
            </collision>
            <xacro:default_inertial mass="10"/>
        </link>

        <joint name="base_to_${prefix}_${suffix}_leg" type="revolute">
            <parent link="base_link"/>
            <child link="${prefix}_${suffix}_leg"/>
            <origin xyz="${reflect_x * (base_x/2)} ${reflect_y * (base_y/2)} 0.0"/>
            <axis xyz="0.0 0.0 1"/>
            <limit lower="-${pi/2}" upper="${pi/2}" effort="${base_effort}" velocity="${base_velocity}"/>
        </joint>
        <xacro:wheel prefix="${prefix}" suffix="${suffix}" />
    </xacro:macro>

    <!-- Wheel macro -->
    <xacro:macro name="wheel" params="prefix suffix"> 
        <link name="${prefix}_${suffix}_wheel">
            <visual>
                <origin rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_diam/2}" length="${wheel_length/2}"/>
                </geometry>
                <material name="black"/>
            </visual>
            <collision>
                <origin rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_diam/2}" length="${wheel_length/2}"/>
                </geometry>
            </collision>
            <xacro:default_inertial mass="1"/>
        </link>

        <joint name="${prefix}_${suffix}_wheel_joint" type="continuous">
            <parent link="${prefix}_${suffix}_leg"/>
            <child link="${prefix}_${suffix}_wheel"/>
            <origin xyz="0.0 0.0 -${leg_z}"/>
            <axis xyz="0.0 1 0.0"/>
        </joint>

    </xacro:macro>

    <xacro:leg prefix="right" suffix="front" reflect_x="-1" reflect_y="-1"/>
    <xacro:leg prefix="left" suffix="front" reflect_x="1" reflect_y="-1"/>
    <xacro:leg prefix="right" suffix="back" reflect_x="-1" reflect_y="1"/>
    <xacro:leg prefix="left" suffix="back" reflect_x="1" reflect_y="1"/>

</robot>