<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="inertials.xacro" />

  <!-- Shoulder measurements-->
  <xacro:property name="shoulder_box_x" value="0.155" />
  <xacro:property name="shoulder_box_y" value="0.080" />
  <xacro:property name="shoulder_box_z" value="0.055" />
  <xacro:property name="shoulder_box_weight" value="0.050" />

  <xacro:property name="shoulder_horizontal_x" value="0.040" />
  <xacro:property name="shoulder_horizontal_y" value="0.085" />
  <xacro:property name="shoulder_horizontal_z" value="0.020" />
  <xacro:property name="shoulder_horizontal_weight" value="0.07241" />

  <xacro:property name="shoulder_vertical_x" value="0.305" />
  <xacro:property name="shoulder_vertical_y" value="0.020" />
  <xacro:property name="shoulder_vertical_z" value="0.060" />
  <xacro:property name="shoulder_vertical_weight" value="0.23928" />

  <!-- Center of the robot -->
  <xacro:property name="main_link_x" value="0.040" />
  <xacro:property name="main_link_y" value="0.100" />
  <xacro:property name="main_link_z" value="0.020" />
  <xacro:property name="main_link_weight" value="0.08519" />

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0.0 0.0 0.0" />
      <geometry>
        <box
          size="
                    ${main_link_x}
                    ${main_link_y}
                    ${main_link_z}" />
      </geometry>
      <material name="blue" />
    </visual>
    <collision>
      <origin xyz="0.0 0.0 0.0" />
      <geometry>
        <box
          size="
                    ${main_link_x}
                    ${main_link_y}
                    ${main_link_z}" />
      </geometry>
    </collision>
    <!-- <xacro:default_inertial mass="${main_link_weight}" /> -->
  </link>


  <xacro:macro name="shoulder" params="prefix suffix reflect_y">
    <link name="${prefix}_shoulder_horizontal">
      <xacro:default_inertial mass="${shoulder_horizontal_weight}" />
      <visual>
        <origin xyz="0.0 0.0 0.0" />
        <geometry>
          <box
            size="${shoulder_horizontal_x} 
                    ${shoulder_horizontal_y}
                    ${shoulder_horizontal_z}" />
        </geometry>
        <material name="red" />
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" />
        <geometry>
          <box
            size="${shoulder_horizontal_x} 
                    ${shoulder_horizontal_y}
                    ${shoulder_horizontal_z}" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_shoulder_horizontal_base" type="fixed">
      <origin
        xyz="
            0.0 
            ${reflect_y *((shoulder_horizontal_y / 2) + (main_link_y / 2))} 
            0.0" />
      <parent link="base_link" />
      <child link="${prefix}_shoulder_horizontal" />
      <axis xyz="0 1 0" />
    </joint>

    <link name="${prefix}_shoulder_box">
      <xacro:default_inertial mass="${shoulder_box_weight}" />
      <visual>
        <origin xyz="0.0 0.0 0.0" />
        <geometry>
          <box
            size="
                        ${shoulder_box_x} 
                        ${shoulder_box_y} 
                        ${shoulder_box_z}"
          />
        </geometry>
        <material name="green" />
      </visual>
      <collision>
        <origin xyz="0.0 0.0 0.0" />
        <geometry>
          <box
            size="
                        ${shoulder_box_x} 
                        ${shoulder_box_y} 
                        ${shoulder_box_z}"
          />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_shoulder_box_shoulder" type="fixed">
      <origin
        xyz="
            0
            ${reflect_y * (shoulder_horizontal_y / 4)}
            ${(shoulder_horizontal_z / 2) + (shoulder_box_z / 2)}" />
      <parent link="${prefix}_shoulder_horizontal" />
      <child link="${prefix}_shoulder_box" />
    </joint>

    <link name="${prefix}_shoulder_vertical">
      <xacro:default_inertial mass="${shoulder_vertical_weight}" />
      <visual>
        <origin xyz="0 0.0 0.0" />
        <geometry>
          <box
            size="
                    ${shoulder_vertical_x}
                    ${shoulder_vertical_y}
                    ${shoulder_vertical_z}" />
        </geometry>
        <material name="white" />
      </visual>
      <collision>
        <origin xyz="0 0.0 0.0" />
        <geometry>
          <box
            size="
                    ${shoulder_vertical_x}
                    ${shoulder_vertical_y}
                    ${shoulder_vertical_z}" />
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_shoulder_joint" type="fixed">
      <origin
        xyz="
            0
            ${reflect_y * ((shoulder_horizontal_y / 2) + (shoulder_vertical_y / 2))}            
            ${-1 * (shoulder_vertical_z/2 - shoulder_horizontal_z/2)}" />
      <parent link="${prefix}_shoulder_horizontal" />
      <child link="${prefix}_shoulder_vertical" />
    </joint>
  </xacro:macro>
</robot>
